### ISSUE TITLE
Add Party Teaming in Team Games

### ISSUE THREAD

**Issue by Altamash347** [pretendlake/Parties#4]
It would be great if you add Teaming with Party.

Example: 
BedWars is a Teaming game, so make it like the players in the same party should join the same team in BedWars.

**Comment by pretendlake** [comment]
You can implement party teaming in your own plugin. In order to do that, you would have to check if the player who joins a match is the party leader and if so, get all the members from their party and add them into the same match with the same team.

If you need help on doing this, you can join this discord: [![Discord](https://img.shields.io/discord/732039634745425972?color=%2392e5fc&label=discord)](https://discord.gg/bsFSwTR)
If you want a public plugin to be compatible with parties, contact the plugin author.
